[FEAT] 투표 현황 조회 API
TeamPiickle/server pull request #64
Opened 2022-07-14 16:40 UTC by DongLee99

**우선순위**

D-

**변경사항**

**유의사항**

**참조**

2022-07-15 07:44 UTC, kyY00n requested changes
두 상황을 한번에 처리해야해서 고민이 많으셨을것 같아용 수고하셨슴다 🕺
궁금한 점과 제 생각들 코멘트 달았으니 확인해주세요~!

2022-07-15 07:44 UTC, kyY00n commented on src/middlewares/flexibleAuth.ts
> +    };
p3. 명시적으로 null을 선언한 이유가 궁금해요. 꼭 필요한 연산인지 같이 고민해보고싶어요

2022-07-15 07:44 UTC, kyY00n commented on src/controllers/ballotController.ts
> +    const userId = req.user.id as Types.ObjectId;
p3. flexibleAuth의 연산에 따라 req.user.id는 null이 되는 경우가 분명히 존재하는데 타입 단언을 사용해도 괜찮을까요?

2022-07-15 07:44 UTC, kyY00n commented on src/services/ballotService.ts
> +  });
질문. ballotTopicId 가 올바르지 않은 경우 어떻게 될지 궁금합니다

2022-07-15 07:44 UTC, kyY00n commented on src/services/ballotService.ts
> +  );
p2. Promise.all 사용하지 않아도 될 것 같아요!

2022-07-15 07:44 UTC, kyY00n commented on src/services/ballotService.ts
> +        ),
p4. 다른 곳에서 계산해서 result에 넣어주면 가독성이 좋아질 것 같아요

2022-07-15 07:44 UTC, kyY00n commented on src/services/ballotService.ts
> +    )
한 방에 때려넣는걸 좋아하시는군요 동현님

2022-07-17 06:36 UTC, DongLee99 commented on src/services/ballotService.ts
> +  );
Promise.all 안쓰니까 비동기 처리가 안돼요 ㅜ

2022-07-17 07:36 UTC, kyY00n approved these changes
수고했어욥!

2022-07-17 07:43 UTC, merged